#!/usr/local/bin/bash
# ©2009 Randy <randy@cyberhosters.org>
TUN=vr0                                          # tunnel device for IPv6 IP's
EXCLUDE="2001:470:c:2e8::2"                      # IP's to exclude from vhost listing
IFCONFIG=/sbin/ifconfig
HOST=`which host`
DATE=`date "+%Y-%m-%d%n"`
TIME=`date "+%H:%M:%S"`
DGRAY="\e[1;30m"
PINK="\e[1;31m"
TEAL="\e[01;32m"
WHITE="\e[1;37m"
GREEN="\e[1;32m"
PISS="\e[0;33m"
GRAY="\e[0;37m"
BLUE="\e[1;34m"
YELLOW="\e[1;33m"
COL5="\e[1;32m";
COLOFF="\x1b[0;37;00m";
RESET="\e[0m"
TOTAL=0
UP=0
DOWN=0
IPS="`$IFCONFIG | grep -w inet | grep -v 127.0.0.1 | awk '{print $2}' | sed "s/addr://"`"
SOCKSTATS="/usr/local/bin/sockstats"

echo -e "  _    _ _     _  _____  _______ _______ _______"
echo -e "   \  /  |_____| |     | |______    |    |______"
echo -e "    \/   |     | |_____| ______|    |    ______|"
printf "\n\nSystem: ${BLUE}${HOSTNAME}${COLOFF} "
printf "\n\n "
echo -e "IP Address   Hostname       (unique users) (sockets)"
echo -e " "
for EACH in $IPS; do
 SOCKETS=0
 UNIQUE=0
 if [ "`echo $EXCLUDE | grep -w $EACH`" == "" ]; then
  HOSTNAME=`$HOST $EACH | grep "domain" | awk '{print $5}' | sed "s/.$//" 2>/dev/null`
  if [ "$HOSTNAME" == "" ]; then
   HOSTNAME="localhost"
  fi
  if [ "`echo $EACH | grep ":"`" == "" ]; then
   IP=`$HOST -t A $HOSTNAME | awk '{print $4}' 2>/dev/null`
  else
   IP=`$HOST -t AAAA $HOSTNAME | awk '{print $5}' 2>/dev/null`
  fi
  DATA=`$SOCKSTATS $EACH 2>/dev/null`
  UNIQUE=`echo $DATA | awk '{print $1}'`
  SOCKETS=`echo $DATA | awk '{print $2}'`
  if [ "$EACH" == "$IP" ]; then
   echo -e " ${TEAL}${IP} ${GRAY}- ${WHITE}${HOSTNAME} ${DGRAY}(${GRAY}${UNIQUE}${DGRAY})   ${DGRAY}(${GRAY}${SOCKETS}${DGRAY})"
   UP=`expr $UP + 1`
  else
   echo -e " ${TEAL}${EACH} ${GRAY}- ${DGRAY}${HOSTNAME} ${DGRAY}(${GRAY}${UNIQUE}${DGRAY})   ${DGRAY}(${GRAY}${SOCKETS}${DGRAY})"
   DOWN=`expr $DOWN + 1`
  fi
 fi
 TOTAL=`expr $TOTAL + 1`
done
echo -e ""
echo -e "${GRAY}Up: ${TEAL}${UP} ${GRAY}Down: ${PINK}$DOWN ${GRAY}Total: ${WHITE}${TOTAL}${RESET}"
echo -e "${GRAY}Note: Gray hostname means it may not resolve properly"
echo -e "To see VHosts List on the web go to:"
echo -e "${BLUE}http://www.CyberHosters.org/gemini.php"
echo -e "${WHITE}Thank You for using CyberHosters.org"
